return function()
    require'nvim-treesitter.configs'.setup {
        ensure_installed = {
            'bash',
            'c',
            'cmake',
            'comment',
            'cpp',
            'css',
            'dockerfile',
            'git_rebase',
            'gitcommit',
            'gitignore',
            'go',
            'gomod',
            'gosum',
            'gowork',
            'html',
            'java',
            'javascript',
            'jsdoc',
            'jsonc',
            'latex',
            'linkerscript',
            'lua',
            'markdown',
            'mermaid',
            'python',
            'ron',
            'rust',
            'sql',
            'svelte',
            'toml',
            'tsx',
            'typescript',
            'vim',
            'yaml',
            'zig',
        },
        indent = { enable = true },
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
    }
end
